@id=2cc5e8e7-34de-4708-882f-cbd0939a418c

PUT http://localhost:5107/api/tests/{{id}}
Content-Type: application/json

{
    "OrderId": "ca275ab8-0510-415e-9373-97e02f94ced9",
    "DateTimeOrdered": "2023-10-01T12:00:00",
    "Result": "Positive"
}