@id=08aa1011-cf1f-4ce1-9956-b06d5ad004c0

PUT http://localhost:5107/api/patients/{{id}}
Content-Type: application/json

{
    "FirstName": "Sue",
    "LastName": "Thompson",
    "DateOfBirth": "1963-10-22"
}