@id=94a7bcb9-41ef-430c-bc95-6f139a503ebd

PUT http://localhost:5107/api/orders/{{id}}
Content-Type: application/json

{
    "PatientId": "f8d0ee4e-abc0-4ed0-b680-dbbd34b2d6e1",
    "OrderType": "C# !!",
    "Notes": "Test order notes."
}